// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module a0_resetCurrentSliceHW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        glPLSlices_0_address0,
        glPLSlices_0_ce0,
        glPLSlices_0_we0,
        glPLSlices_0_d0,
        glPLSlices_0_address1,
        glPLSlices_0_ce1,
        glPLSlices_0_we1,
        glPLSlices_0_d1,
        glPLSlices_1_address0,
        glPLSlices_1_ce0,
        glPLSlices_1_we0,
        glPLSlices_1_d0,
        glPLSlices_1_address1,
        glPLSlices_1_ce1,
        glPLSlices_1_we1,
        glPLSlices_1_d1,
        glPLSlices_2_address0,
        glPLSlices_2_ce0,
        glPLSlices_2_we0,
        glPLSlices_2_d0,
        glPLSlices_2_address1,
        glPLSlices_2_ce1,
        glPLSlices_2_we1,
        glPLSlices_2_d1,
        glPLSlices_3_address0,
        glPLSlices_3_ce0,
        glPLSlices_3_we0,
        glPLSlices_3_d0,
        glPLSlices_3_address1,
        glPLSlices_3_ce1,
        glPLSlices_3_we1,
        glPLSlices_3_d1,
        glPLSlices_4_address0,
        glPLSlices_4_ce0,
        glPLSlices_4_we0,
        glPLSlices_4_d0,
        glPLSlices_4_address1,
        glPLSlices_4_ce1,
        glPLSlices_4_we1,
        glPLSlices_4_d1,
        glPLSlices_5_address0,
        glPLSlices_5_ce0,
        glPLSlices_5_we0,
        glPLSlices_5_d0,
        glPLSlices_5_address1,
        glPLSlices_5_ce1,
        glPLSlices_5_we1,
        glPLSlices_5_d1,
        glPLSlices_6_address0,
        glPLSlices_6_ce0,
        glPLSlices_6_we0,
        glPLSlices_6_d0,
        glPLSlices_6_address1,
        glPLSlices_6_ce1,
        glPLSlices_6_we1,
        glPLSlices_6_d1,
        glPLSlices_7_address0,
        glPLSlices_7_ce0,
        glPLSlices_7_we0,
        glPLSlices_7_d0,
        glPLSlices_7_address1,
        glPLSlices_7_ce1,
        glPLSlices_7_we1,
        glPLSlices_7_d1,
        glPLSlices_8_address0,
        glPLSlices_8_ce0,
        glPLSlices_8_we0,
        glPLSlices_8_d0,
        glPLSlices_8_address1,
        glPLSlices_8_ce1,
        glPLSlices_8_we1,
        glPLSlices_8_d1,
        glPLSlices_9_address0,
        glPLSlices_9_ce0,
        glPLSlices_9_we0,
        glPLSlices_9_d0,
        glPLSlices_9_address1,
        glPLSlices_9_ce1,
        glPLSlices_9_we1,
        glPLSlices_9_d1,
        glPLSlices_10_address0,
        glPLSlices_10_ce0,
        glPLSlices_10_we0,
        glPLSlices_10_d0,
        glPLSlices_10_address1,
        glPLSlices_10_ce1,
        glPLSlices_10_we1,
        glPLSlices_10_d1,
        glPLSlices_11_address0,
        glPLSlices_11_ce0,
        glPLSlices_11_we0,
        glPLSlices_11_d0,
        glPLSlices_11_address1,
        glPLSlices_11_ce1,
        glPLSlices_11_we1,
        glPLSlices_11_d1,
        glPLSlices_12_address0,
        glPLSlices_12_ce0,
        glPLSlices_12_we0,
        glPLSlices_12_d0,
        glPLSlices_12_address1,
        glPLSlices_12_ce1,
        glPLSlices_12_we1,
        glPLSlices_12_d1,
        glPLSlices_13_address0,
        glPLSlices_13_ce0,
        glPLSlices_13_we0,
        glPLSlices_13_d0,
        glPLSlices_13_address1,
        glPLSlices_13_ce1,
        glPLSlices_13_we1,
        glPLSlices_13_d1,
        glPLSlices_14_address0,
        glPLSlices_14_ce0,
        glPLSlices_14_we0,
        glPLSlices_14_d0,
        glPLSlices_14_address1,
        glPLSlices_14_ce1,
        glPLSlices_14_we1,
        glPLSlices_14_d1,
        glPLSlices_15_address0,
        glPLSlices_15_ce0,
        glPLSlices_15_we0,
        glPLSlices_15_d0,
        glPLSlices_15_address1,
        glPLSlices_15_ce1,
        glPLSlices_15_we1,
        glPLSlices_15_d1
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] glPLSlices_0_address0;
output   glPLSlices_0_ce0;
output   glPLSlices_0_we0;
output  [7:0] glPLSlices_0_d0;
output  [12:0] glPLSlices_0_address1;
output   glPLSlices_0_ce1;
output   glPLSlices_0_we1;
output  [7:0] glPLSlices_0_d1;
output  [12:0] glPLSlices_1_address0;
output   glPLSlices_1_ce0;
output   glPLSlices_1_we0;
output  [7:0] glPLSlices_1_d0;
output  [12:0] glPLSlices_1_address1;
output   glPLSlices_1_ce1;
output   glPLSlices_1_we1;
output  [7:0] glPLSlices_1_d1;
output  [12:0] glPLSlices_2_address0;
output   glPLSlices_2_ce0;
output   glPLSlices_2_we0;
output  [7:0] glPLSlices_2_d0;
output  [12:0] glPLSlices_2_address1;
output   glPLSlices_2_ce1;
output   glPLSlices_2_we1;
output  [7:0] glPLSlices_2_d1;
output  [12:0] glPLSlices_3_address0;
output   glPLSlices_3_ce0;
output   glPLSlices_3_we0;
output  [7:0] glPLSlices_3_d0;
output  [12:0] glPLSlices_3_address1;
output   glPLSlices_3_ce1;
output   glPLSlices_3_we1;
output  [7:0] glPLSlices_3_d1;
output  [12:0] glPLSlices_4_address0;
output   glPLSlices_4_ce0;
output   glPLSlices_4_we0;
output  [7:0] glPLSlices_4_d0;
output  [12:0] glPLSlices_4_address1;
output   glPLSlices_4_ce1;
output   glPLSlices_4_we1;
output  [7:0] glPLSlices_4_d1;
output  [12:0] glPLSlices_5_address0;
output   glPLSlices_5_ce0;
output   glPLSlices_5_we0;
output  [7:0] glPLSlices_5_d0;
output  [12:0] glPLSlices_5_address1;
output   glPLSlices_5_ce1;
output   glPLSlices_5_we1;
output  [7:0] glPLSlices_5_d1;
output  [12:0] glPLSlices_6_address0;
output   glPLSlices_6_ce0;
output   glPLSlices_6_we0;
output  [7:0] glPLSlices_6_d0;
output  [12:0] glPLSlices_6_address1;
output   glPLSlices_6_ce1;
output   glPLSlices_6_we1;
output  [7:0] glPLSlices_6_d1;
output  [12:0] glPLSlices_7_address0;
output   glPLSlices_7_ce0;
output   glPLSlices_7_we0;
output  [7:0] glPLSlices_7_d0;
output  [12:0] glPLSlices_7_address1;
output   glPLSlices_7_ce1;
output   glPLSlices_7_we1;
output  [7:0] glPLSlices_7_d1;
output  [12:0] glPLSlices_8_address0;
output   glPLSlices_8_ce0;
output   glPLSlices_8_we0;
output  [7:0] glPLSlices_8_d0;
output  [12:0] glPLSlices_8_address1;
output   glPLSlices_8_ce1;
output   glPLSlices_8_we1;
output  [7:0] glPLSlices_8_d1;
output  [12:0] glPLSlices_9_address0;
output   glPLSlices_9_ce0;
output   glPLSlices_9_we0;
output  [7:0] glPLSlices_9_d0;
output  [12:0] glPLSlices_9_address1;
output   glPLSlices_9_ce1;
output   glPLSlices_9_we1;
output  [7:0] glPLSlices_9_d1;
output  [12:0] glPLSlices_10_address0;
output   glPLSlices_10_ce0;
output   glPLSlices_10_we0;
output  [7:0] glPLSlices_10_d0;
output  [12:0] glPLSlices_10_address1;
output   glPLSlices_10_ce1;
output   glPLSlices_10_we1;
output  [7:0] glPLSlices_10_d1;
output  [12:0] glPLSlices_11_address0;
output   glPLSlices_11_ce0;
output   glPLSlices_11_we0;
output  [7:0] glPLSlices_11_d0;
output  [12:0] glPLSlices_11_address1;
output   glPLSlices_11_ce1;
output   glPLSlices_11_we1;
output  [7:0] glPLSlices_11_d1;
output  [12:0] glPLSlices_12_address0;
output   glPLSlices_12_ce0;
output   glPLSlices_12_we0;
output  [7:0] glPLSlices_12_d0;
output  [12:0] glPLSlices_12_address1;
output   glPLSlices_12_ce1;
output   glPLSlices_12_we1;
output  [7:0] glPLSlices_12_d1;
output  [12:0] glPLSlices_13_address0;
output   glPLSlices_13_ce0;
output   glPLSlices_13_we0;
output  [7:0] glPLSlices_13_d0;
output  [12:0] glPLSlices_13_address1;
output   glPLSlices_13_ce1;
output   glPLSlices_13_we1;
output  [7:0] glPLSlices_13_d1;
output  [12:0] glPLSlices_14_address0;
output   glPLSlices_14_ce0;
output   glPLSlices_14_we0;
output  [7:0] glPLSlices_14_d0;
output  [12:0] glPLSlices_14_address1;
output   glPLSlices_14_ce1;
output   glPLSlices_14_we1;
output  [7:0] glPLSlices_14_d1;
output  [12:0] glPLSlices_15_address0;
output   glPLSlices_15_ce0;
output   glPLSlices_15_we0;
output  [7:0] glPLSlices_15_d0;
output  [12:0] glPLSlices_15_address1;
output   glPLSlices_15_ce1;
output   glPLSlices_15_we1;
output  [7:0] glPLSlices_15_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] glPLSlices_0_address0;
reg glPLSlices_0_ce0;
reg glPLSlices_0_we0;
reg[12:0] glPLSlices_0_address1;
reg glPLSlices_0_ce1;
reg glPLSlices_0_we1;
reg[12:0] glPLSlices_1_address0;
reg glPLSlices_1_ce0;
reg glPLSlices_1_we0;
reg[12:0] glPLSlices_1_address1;
reg glPLSlices_1_ce1;
reg glPLSlices_1_we1;
reg[12:0] glPLSlices_2_address0;
reg glPLSlices_2_ce0;
reg glPLSlices_2_we0;
reg[12:0] glPLSlices_2_address1;
reg glPLSlices_2_ce1;
reg glPLSlices_2_we1;
reg[12:0] glPLSlices_3_address0;
reg glPLSlices_3_ce0;
reg glPLSlices_3_we0;
reg[12:0] glPLSlices_3_address1;
reg glPLSlices_3_ce1;
reg glPLSlices_3_we1;
reg[12:0] glPLSlices_4_address0;
reg glPLSlices_4_ce0;
reg glPLSlices_4_we0;
reg[12:0] glPLSlices_4_address1;
reg glPLSlices_4_ce1;
reg glPLSlices_4_we1;
reg[12:0] glPLSlices_5_address0;
reg glPLSlices_5_ce0;
reg glPLSlices_5_we0;
reg[12:0] glPLSlices_5_address1;
reg glPLSlices_5_ce1;
reg glPLSlices_5_we1;
reg[12:0] glPLSlices_6_address0;
reg glPLSlices_6_ce0;
reg glPLSlices_6_we0;
reg[12:0] glPLSlices_6_address1;
reg glPLSlices_6_ce1;
reg glPLSlices_6_we1;
reg[12:0] glPLSlices_7_address0;
reg glPLSlices_7_ce0;
reg glPLSlices_7_we0;
reg[12:0] glPLSlices_7_address1;
reg glPLSlices_7_ce1;
reg glPLSlices_7_we1;
reg[12:0] glPLSlices_8_address0;
reg glPLSlices_8_ce0;
reg glPLSlices_8_we0;
reg[12:0] glPLSlices_8_address1;
reg glPLSlices_8_ce1;
reg glPLSlices_8_we1;
reg[12:0] glPLSlices_9_address0;
reg glPLSlices_9_ce0;
reg glPLSlices_9_we0;
reg[12:0] glPLSlices_9_address1;
reg glPLSlices_9_ce1;
reg glPLSlices_9_we1;
reg[12:0] glPLSlices_10_address0;
reg glPLSlices_10_ce0;
reg glPLSlices_10_we0;
reg[12:0] glPLSlices_10_address1;
reg glPLSlices_10_ce1;
reg glPLSlices_10_we1;
reg[12:0] glPLSlices_11_address0;
reg glPLSlices_11_ce0;
reg glPLSlices_11_we0;
reg[12:0] glPLSlices_11_address1;
reg glPLSlices_11_ce1;
reg glPLSlices_11_we1;
reg[12:0] glPLSlices_12_address0;
reg glPLSlices_12_ce0;
reg glPLSlices_12_we0;
reg[12:0] glPLSlices_12_address1;
reg glPLSlices_12_ce1;
reg glPLSlices_12_we1;
reg[12:0] glPLSlices_13_address0;
reg glPLSlices_13_ce0;
reg glPLSlices_13_we0;
reg[12:0] glPLSlices_13_address1;
reg glPLSlices_13_ce1;
reg glPLSlices_13_we1;
reg[12:0] glPLSlices_14_address0;
reg glPLSlices_14_ce0;
reg glPLSlices_14_we0;
reg[12:0] glPLSlices_14_address1;
reg glPLSlices_14_ce1;
reg glPLSlices_14_we1;
reg[12:0] glPLSlices_15_address0;
reg glPLSlices_15_ce0;
reg glPLSlices_15_we0;
reg[12:0] glPLSlices_15_address1;
reg glPLSlices_15_ce1;
reg glPLSlices_15_we1;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] i_1_fu_2173_p2;
reg   [7:0] i_1_reg_2579;
wire    ap_CS_fsm_state2;
wire  signed [13:0] tmp_3_cast1_fu_2201_p1;
reg  signed [13:0] tmp_3_cast1_reg_2584;
wire   [0:0] exitcond1_fu_2167_p2;
reg   [7:0] i_reg_2156;
wire    ap_CS_fsm_state9;
wire  signed [31:0] tmp_3_cast_fu_2205_p1;
wire  signed [31:0] tmp_4_cast_fu_2231_p1;
wire  signed [31:0] tmp_5_cast_fu_2256_p1;
wire    ap_CS_fsm_state3;
wire  signed [31:0] tmp_6_cast_fu_2281_p1;
wire  signed [31:0] tmp_7_cast_fu_2306_p1;
wire    ap_CS_fsm_state4;
wire  signed [31:0] tmp_8_cast_fu_2331_p1;
wire  signed [31:0] tmp_9_cast_fu_2356_p1;
wire    ap_CS_fsm_state5;
wire  signed [31:0] tmp_10_cast_fu_2381_p1;
wire  signed [31:0] tmp_11_cast_fu_2406_p1;
wire    ap_CS_fsm_state6;
wire  signed [31:0] tmp_12_cast_fu_2431_p1;
wire  signed [31:0] tmp_13_cast_fu_2456_p1;
wire    ap_CS_fsm_state7;
wire  signed [31:0] tmp_14_cast_fu_2481_p1;
wire  signed [31:0] tmp_15_cast_fu_2506_p1;
wire    ap_CS_fsm_state8;
wire  signed [31:0] tmp_16_cast_fu_2531_p1;
wire  signed [31:0] tmp_17_cast_fu_2556_p1;
wire   [11:0] tmp_2_fu_2183_p3;
wire   [12:0] p_shl_cast_fu_2191_p1;
wire   [12:0] tmp_cast_fu_2179_p1;
wire  signed [12:0] tmp_3_fu_2195_p2;
wire   [13:0] tmp_4_fu_2225_p2;
wire   [13:0] tmp_5_fu_2251_p2;
wire   [13:0] tmp_6_fu_2276_p2;
wire   [13:0] tmp_7_fu_2301_p2;
wire   [13:0] tmp_8_fu_2326_p2;
wire   [13:0] tmp_9_fu_2351_p2;
wire   [13:0] tmp_s_fu_2376_p2;
wire   [13:0] tmp_10_fu_2401_p2;
wire   [13:0] tmp_11_fu_2426_p2;
wire   [13:0] tmp_12_fu_2451_p2;
wire   [13:0] tmp_13_fu_2476_p2;
wire   [13:0] tmp_14_fu_2501_p2;
wire   [13:0] tmp_15_fu_2526_p2;
wire   [13:0] tmp_16_fu_2551_p2;
wire    ap_CS_fsm_state10;
reg   [9:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_reg_2156 <= i_1_reg_2579;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_2156 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_2579 <= i_1_fu_2173_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_3_cast1_reg_2584 <= tmp_3_cast1_fu_2201_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_0_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_0_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_0_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_0_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_0_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_0_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_0_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_0_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_0_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_0_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_0_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_0_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_0_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_0_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_0_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_0_ce0 = 1'b1;
    end else begin
        glPLSlices_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_0_ce1 = 1'b1;
    end else begin
        glPLSlices_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_0_we0 = 1'b1;
    end else begin
        glPLSlices_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_0_we1 = 1'b1;
    end else begin
        glPLSlices_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_10_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_10_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_10_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_10_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_10_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_10_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_10_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_10_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_10_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_10_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_10_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_10_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_10_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_10_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_10_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_10_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_10_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_10_ce0 = 1'b1;
    end else begin
        glPLSlices_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_10_ce1 = 1'b1;
    end else begin
        glPLSlices_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_10_we0 = 1'b1;
    end else begin
        glPLSlices_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_10_we1 = 1'b1;
    end else begin
        glPLSlices_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_11_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_11_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_11_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_11_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_11_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_11_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_11_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_11_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_11_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_11_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_11_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_11_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_11_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_11_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_11_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_11_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_11_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_11_ce0 = 1'b1;
    end else begin
        glPLSlices_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_11_ce1 = 1'b1;
    end else begin
        glPLSlices_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_11_we0 = 1'b1;
    end else begin
        glPLSlices_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_11_we1 = 1'b1;
    end else begin
        glPLSlices_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_12_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_12_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_12_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_12_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_12_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_12_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_12_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_12_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_12_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_12_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_12_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_12_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_12_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_12_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_12_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_12_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_12_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_12_ce0 = 1'b1;
    end else begin
        glPLSlices_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_12_ce1 = 1'b1;
    end else begin
        glPLSlices_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_12_we0 = 1'b1;
    end else begin
        glPLSlices_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_12_we1 = 1'b1;
    end else begin
        glPLSlices_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_13_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_13_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_13_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_13_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_13_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_13_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_13_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_13_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_13_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_13_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_13_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_13_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_13_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_13_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_13_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_13_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_13_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_13_ce0 = 1'b1;
    end else begin
        glPLSlices_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_13_ce1 = 1'b1;
    end else begin
        glPLSlices_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_13_we0 = 1'b1;
    end else begin
        glPLSlices_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_13_we1 = 1'b1;
    end else begin
        glPLSlices_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_14_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_14_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_14_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_14_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_14_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_14_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_14_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_14_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_14_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_14_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_14_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_14_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_14_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_14_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_14_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_14_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_14_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_14_ce0 = 1'b1;
    end else begin
        glPLSlices_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_14_ce1 = 1'b1;
    end else begin
        glPLSlices_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_14_we0 = 1'b1;
    end else begin
        glPLSlices_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_14_we1 = 1'b1;
    end else begin
        glPLSlices_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_15_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_15_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_15_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_15_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_15_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_15_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_15_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_15_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_15_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_15_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_15_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_15_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_15_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_15_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_15_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_15_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_15_ce0 = 1'b1;
    end else begin
        glPLSlices_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_15_ce1 = 1'b1;
    end else begin
        glPLSlices_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_15_we0 = 1'b1;
    end else begin
        glPLSlices_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_15_we1 = 1'b1;
    end else begin
        glPLSlices_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_1_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_1_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_1_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_1_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_1_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_1_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_1_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_1_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_1_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_1_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_1_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_1_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_1_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_1_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_1_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_1_ce0 = 1'b1;
    end else begin
        glPLSlices_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_1_ce1 = 1'b1;
    end else begin
        glPLSlices_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_1_we0 = 1'b1;
    end else begin
        glPLSlices_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_1_we1 = 1'b1;
    end else begin
        glPLSlices_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_2_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_2_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_2_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_2_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_2_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_2_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_2_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_2_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_2_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_2_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_2_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_2_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_2_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_2_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_2_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_2_ce0 = 1'b1;
    end else begin
        glPLSlices_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_2_ce1 = 1'b1;
    end else begin
        glPLSlices_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_2_we0 = 1'b1;
    end else begin
        glPLSlices_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_2_we1 = 1'b1;
    end else begin
        glPLSlices_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_3_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_3_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_3_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_3_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_3_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_3_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_3_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_3_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_3_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_3_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_3_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_3_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_3_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_3_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_3_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_3_ce0 = 1'b1;
    end else begin
        glPLSlices_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_3_ce1 = 1'b1;
    end else begin
        glPLSlices_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_3_we0 = 1'b1;
    end else begin
        glPLSlices_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_3_we1 = 1'b1;
    end else begin
        glPLSlices_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_4_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_4_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_4_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_4_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_4_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_4_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_4_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_4_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_4_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_4_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_4_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_4_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_4_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_4_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_4_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_4_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_4_ce0 = 1'b1;
    end else begin
        glPLSlices_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_4_ce1 = 1'b1;
    end else begin
        glPLSlices_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_4_we0 = 1'b1;
    end else begin
        glPLSlices_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_4_we1 = 1'b1;
    end else begin
        glPLSlices_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_5_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_5_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_5_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_5_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_5_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_5_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_5_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_5_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_5_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_5_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_5_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_5_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_5_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_5_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_5_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_5_ce0 = 1'b1;
    end else begin
        glPLSlices_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_5_ce1 = 1'b1;
    end else begin
        glPLSlices_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_5_we0 = 1'b1;
    end else begin
        glPLSlices_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_5_we1 = 1'b1;
    end else begin
        glPLSlices_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_6_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_6_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_6_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_6_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_6_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_6_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_6_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_6_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_6_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_6_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_6_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_6_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_6_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_6_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_6_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_6_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_6_ce0 = 1'b1;
    end else begin
        glPLSlices_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_6_ce1 = 1'b1;
    end else begin
        glPLSlices_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_6_we0 = 1'b1;
    end else begin
        glPLSlices_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_6_we1 = 1'b1;
    end else begin
        glPLSlices_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_7_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_7_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_7_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_7_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_7_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_7_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_7_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_7_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_7_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_7_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_7_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_7_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_7_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_7_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_7_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_7_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_7_ce0 = 1'b1;
    end else begin
        glPLSlices_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_7_ce1 = 1'b1;
    end else begin
        glPLSlices_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_7_we0 = 1'b1;
    end else begin
        glPLSlices_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_7_we1 = 1'b1;
    end else begin
        glPLSlices_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_8_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_8_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_8_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_8_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_8_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_8_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_8_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_8_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_8_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_8_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_8_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_8_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_8_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_8_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_8_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_8_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_8_ce0 = 1'b1;
    end else begin
        glPLSlices_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_8_ce1 = 1'b1;
    end else begin
        glPLSlices_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_8_we0 = 1'b1;
    end else begin
        glPLSlices_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_8_we1 = 1'b1;
    end else begin
        glPLSlices_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        glPLSlices_9_address0 = tmp_17_cast_fu_2556_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_9_address0 = tmp_15_cast_fu_2506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_9_address0 = tmp_13_cast_fu_2456_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_9_address0 = tmp_11_cast_fu_2406_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_9_address0 = tmp_9_cast_fu_2356_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_9_address0 = tmp_7_cast_fu_2306_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_9_address0 = tmp_5_cast_fu_2256_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_9_address0 = tmp_3_cast_fu_2205_p1;
    end else begin
        glPLSlices_9_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        glPLSlices_9_address1 = tmp_16_cast_fu_2531_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        glPLSlices_9_address1 = tmp_14_cast_fu_2481_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        glPLSlices_9_address1 = tmp_12_cast_fu_2431_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        glPLSlices_9_address1 = tmp_10_cast_fu_2381_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        glPLSlices_9_address1 = tmp_8_cast_fu_2331_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        glPLSlices_9_address1 = tmp_6_cast_fu_2281_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        glPLSlices_9_address1 = tmp_4_cast_fu_2231_p1;
    end else begin
        glPLSlices_9_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_9_ce0 = 1'b1;
    end else begin
        glPLSlices_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        glPLSlices_9_ce1 = 1'b1;
    end else begin
        glPLSlices_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_9_we0 = 1'b1;
    end else begin
        glPLSlices_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        glPLSlices_9_we1 = 1'b1;
    end else begin
        glPLSlices_9_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_2167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign exitcond1_fu_2167_p2 = ((i_reg_2156 == 8'd180) ? 1'b1 : 1'b0);

assign glPLSlices_0_d0 = 8'd0;

assign glPLSlices_0_d1 = 8'd0;

assign glPLSlices_10_d0 = 8'd0;

assign glPLSlices_10_d1 = 8'd0;

assign glPLSlices_11_d0 = 8'd0;

assign glPLSlices_11_d1 = 8'd0;

assign glPLSlices_12_d0 = 8'd0;

assign glPLSlices_12_d1 = 8'd0;

assign glPLSlices_13_d0 = 8'd0;

assign glPLSlices_13_d1 = 8'd0;

assign glPLSlices_14_d0 = 8'd0;

assign glPLSlices_14_d1 = 8'd0;

assign glPLSlices_15_d0 = 8'd0;

assign glPLSlices_15_d1 = 8'd0;

assign glPLSlices_1_d0 = 8'd0;

assign glPLSlices_1_d1 = 8'd0;

assign glPLSlices_2_d0 = 8'd0;

assign glPLSlices_2_d1 = 8'd0;

assign glPLSlices_3_d0 = 8'd0;

assign glPLSlices_3_d1 = 8'd0;

assign glPLSlices_4_d0 = 8'd0;

assign glPLSlices_4_d1 = 8'd0;

assign glPLSlices_5_d0 = 8'd0;

assign glPLSlices_5_d1 = 8'd0;

assign glPLSlices_6_d0 = 8'd0;

assign glPLSlices_6_d1 = 8'd0;

assign glPLSlices_7_d0 = 8'd0;

assign glPLSlices_7_d1 = 8'd0;

assign glPLSlices_8_d0 = 8'd0;

assign glPLSlices_8_d1 = 8'd0;

assign glPLSlices_9_d0 = 8'd0;

assign glPLSlices_9_d1 = 8'd0;

assign i_1_fu_2173_p2 = (i_reg_2156 + 8'd1);

assign p_shl_cast_fu_2191_p1 = tmp_2_fu_2183_p3;

assign tmp_10_cast_fu_2381_p1 = $signed(tmp_s_fu_2376_p2);

assign tmp_10_fu_2401_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd8));

assign tmp_11_cast_fu_2406_p1 = $signed(tmp_10_fu_2401_p2);

assign tmp_11_fu_2426_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd9));

assign tmp_12_cast_fu_2431_p1 = $signed(tmp_11_fu_2426_p2);

assign tmp_12_fu_2451_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd10));

assign tmp_13_cast_fu_2456_p1 = $signed(tmp_12_fu_2451_p2);

assign tmp_13_fu_2476_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd11));

assign tmp_14_cast_fu_2481_p1 = $signed(tmp_13_fu_2476_p2);

assign tmp_14_fu_2501_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd12));

assign tmp_15_cast_fu_2506_p1 = $signed(tmp_14_fu_2501_p2);

assign tmp_15_fu_2526_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd13));

assign tmp_16_cast_fu_2531_p1 = $signed(tmp_15_fu_2526_p2);

assign tmp_16_fu_2551_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd14));

assign tmp_17_cast_fu_2556_p1 = $signed(tmp_16_fu_2551_p2);

assign tmp_2_fu_2183_p3 = {{i_reg_2156}, {4'd0}};

assign tmp_3_cast1_fu_2201_p1 = tmp_3_fu_2195_p2;

assign tmp_3_cast_fu_2205_p1 = tmp_3_fu_2195_p2;

assign tmp_3_fu_2195_p2 = (p_shl_cast_fu_2191_p1 - tmp_cast_fu_2179_p1);

assign tmp_4_cast_fu_2231_p1 = $signed(tmp_4_fu_2225_p2);

assign tmp_4_fu_2225_p2 = ($signed(tmp_3_cast1_fu_2201_p1) + $signed(14'd1));

assign tmp_5_cast_fu_2256_p1 = $signed(tmp_5_fu_2251_p2);

assign tmp_5_fu_2251_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd2));

assign tmp_6_cast_fu_2281_p1 = $signed(tmp_6_fu_2276_p2);

assign tmp_6_fu_2276_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd3));

assign tmp_7_cast_fu_2306_p1 = $signed(tmp_7_fu_2301_p2);

assign tmp_7_fu_2301_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd4));

assign tmp_8_cast_fu_2331_p1 = $signed(tmp_8_fu_2326_p2);

assign tmp_8_fu_2326_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd5));

assign tmp_9_cast_fu_2356_p1 = $signed(tmp_9_fu_2351_p2);

assign tmp_9_fu_2351_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd6));

assign tmp_cast_fu_2179_p1 = i_reg_2156;

assign tmp_s_fu_2376_p2 = ($signed(tmp_3_cast1_reg_2584) + $signed(14'd7));

endmodule //a0_resetCurrentSliceHW
