lappend pragmaStatus0 {pragma "INTERFACE" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "copyToPS/copyToPS_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "resetCurrentSliceHW/resetSliceLoop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "resetCurrentSliceHW/resetSliceLoop2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "LATENCY" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INTERFACE" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "parseEvents" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "parseEvents/loop_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "LOOP_TRIPCOUNT" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "parseEvents/loop_1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "E:/xfOpenCV/wksp_2018_1/mz_libcaer_OF_HLS/parseEvents/../../mz_libcaer_OF_HLS/ABMOF/abmof_hw_accel.cpp" location "resetCurrentSliceHW" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "glPLSlices"}
